from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from controllers.agent_controller import AgentController
from pydantic import BaseModel
import traceback

router = APIRouter()


class ChatRequest(BaseModel):
    msg: str
    bot_id: str


@router.post("/chat", summary="Synchronous Chat Response")
def chat(request: ChatRequest):
    try:
        controller = AgentController(request.bot_id)
        result = controller.run(request.msg)
        return {
            "bot_id": request.bot_id,
            "reply": result.get("answer"),
            "contexts": result.get("contexts"),
            "latency": result.get("latency")
        }
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )


@router.post("/stream", summary="Real-Time Token Streaming Chat API", response_class=StreamingResponse)
def stream_chat(request: ChatRequest):
    """
    Real-time SSE token streaming endpoint. Streams response text directly as it is generated by Gemini LLM.
    """
    try:
        controller = AgentController(request.bot_id)
        return StreamingResponse(
            controller.stream_run(request.msg),
            media_type="text/plain"
        )
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )